### ISSUE TITLE
Ignore hidden dirs

### ISSUE THREAD

**Issue by drvinceknight** [Nikoleta-v3/blackbook#26]
Hidden directories (`.git/`, `.venv/`) might contain `.ipynb` files, perhaps we should omit them by default?

**Comment by daffidwilde** [comment]
I am inclined to agree. Maybe as a part of #11 there should be an `--all` flag to not ignore them?

**Comment by drvinceknight** [comment]
Yeah good idea I think #11 should aim to mimic black in the command line tool as well. I think there are flags there to say what is omitted and included.

What's best in the mean time:

- Leave as is? (It's "clear" if you know what hidden dirs you have.)
- Change to omit hidden dirs (It's "clearer" if you're not too sure what's happening in your hidden dirs - see #23).

**Comment by daffidwilde** [comment]
I agree that the command line tool should mimic black. With that in mind, is doing the work to implement something that will eventually get chucked a bit pointless? For lack of a better word.

There are always going to be weird edge cases but the bottom line is that this tool is made to be Black for Jupyter notebooks, and Black is Black. So, any and all work should be towards achieving that rather than deviating temporarily to go over it again.

**Comment by drvinceknight** [comment]
So: "Leave as is" for now?

**Comment by daffidwilde** [comment]
Yeah, I think so.

**Comment by drvinceknight** [comment]
Sounds good to me :+1:
